### ISSUE TITLE
Incorporate a new background

### ISSUE THREAD

**Issue by hantuzun** [neu-fi/turkey-relief-dao#14]
To be designed by Damla.

**Comment by hantuzun** [comment]
The assets are available here courtesy of Damilico: https://www.figma.com/file/nPW7ZYZY9g7TCIudIkW37y/ANKA-RELIEF?node-id=0%3A1&t=9qGmwX07TP5eZ2Lc-1

**Comment by hantuzun** [comment]
<img width="687" alt="Screen Shot 2023-02-10 at 17 18 38" src="https://user-images.githubusercontent.com/2770895/218114290-f555cb60-e33a-482e-be9b-89d192bb8c0e.png">

**Comment by haticecs** [comment]
Hi, not only bg image, also the button and learn more need to be updated right?

**Comment by hantuzun** [comment]
Hi @haticecs, yes. I don't think the PR has worked on them, reviewing from mobile at the moment. If not, we should open a new issue for incorporating the new design.

**Comment by haticecs** [comment]
The linked pr is related to the icon change as far as I checked, not this issue. Sure we can. I am looking into this rn.

**Comment by hantuzun** [comment]
@haticecs, there's a good looking PR on this already, please skip this: https://github.com/neu-fi/turkiye-relief-dao/pull/42/files
