### ISSUE TITLE
Sorting organizations functionality

### ISSUE THREAD

**Issue by hantuzun** [neu-fi/turkey-relief-dao#17]
1. The sort dropdown is commented out. Enable that to make sure it looks fine on screens as narrow as 375px (iPhone SE).
2. Add 2 options: "Suggested" (default), "Popular"

Suggested: The order of the array, which is the current implementation.
Popular: Sorted by the popularity parameters.

**Comment by haticecs** [comment]
Hi @hantuzun, I couldn't find the dropdown. In which file it is placed exactly?
