### ISSUE TITLE
Add OG Image

### ISSUE THREAD

**Issue by hantuzun** [neu-fi/turkey-relief-dao#2]

**Comment by tunntun** [comment]
![TRDAO](https://user-images.githubusercontent.com/108955016/218273293-7554559b-9f36-4f35-bd3f-1f6b20625165.png)
should we change this? or is this issue closed?

**Comment by hantuzun** [comment]
The image must be added as an OG meta in the header.

**Comment by hantuzun** [comment]
Thanks for the asset @hatunn!

**Comment by MhmtMutlu** [comment]
I've completed and opened PR for twitter and og meta tags.
