### ISSUE TITLE
Add missing donation options

### ISSUE THREAD

**Issue by hantuzun** [neu-fi/turkey-relief-dao#20]
A. https://www.paribu.com/#/afet-destek
B. https://www.paribu.com/blog/en/news/about-our-disaster-support-plan-and-the-cryptocurrency-donation-system/
C. https://earthquaketurkey.notion.site/Turkiye-Earthquake-Donations-330ba83b6a93442b92fd46a414a928db
D?

**Comment by hantuzun** [comment]
D: https://twitter.com/TheBullduck/status/1624389815016751105

**Comment by oytuncoban** [comment]
This issue can remain open.
Even though #88 have covered most of the missing donation options, there are still missing options from Paribu and BTCTurk.
