### ISSUE TITLE
Add expand (+) button to card headers next to the website button

### ISSUE THREAD

**Issue by hantuzun** [neu-fi/turkey-relief-dao#27]
<img width="629" alt="Screen Shot 2023-02-10 at 15 17 37" src="https://user-images.githubusercontent.com/2770895/218090674-d95d8a43-9328-4617-8fd9-f3fe0b1cb2df.png">

The number of options in some of the organizations is close to 20.

We should design this experience, especially tailored towards mobile phones.

A few options:

1. The "donation types" and "cryptocurrency networks" filters could be opt-in, instead of opt-out.
2. Every organization could have up to 3 options marked as "featured", and the rest could be extended, or contracted.

We need design help on this issue.

**Comment by tervelix** [comment]
how can i edit website design? 

Organization names should be like a button. Users can click it and open donation adresses.

![image](https://user-images.githubusercontent.com/88801996/218263154-4f897de3-3cd6-4560-84fe-0969ff62bbc3.png)

**Comment by TeenaBatra** [comment]
One suggestion from me:
- We can incorporate a scrollbar if any organisation has more than 3 or 4 options.

**Comment by tunntun** [comment]
> 

https://user-images.githubusercontent.com/108955016/218275327-b7aaf40e-5fc8-44bc-ab7f-e506934ec34a.mov

maybe we can list all the names first and they can click and check everything

**Comment by tunntun** [comment]
https://user-images.githubusercontent.com/108955016/218281743-1f54be9a-5a4f-46a7-8a59-d5e6e36edfc2.mov

or this kind of View button can help people to understand it is clickable

**Comment by tervelix** [comment]
Yes, i was referring this kind of design. Second one would be better.

**Comment by hantuzun** [comment]
Yes, I like the second one too. Could be even better if the icon could be a [ + ] button on the top right, next to the website button.

**Comment by tunntun** [comment]
https://user-images.githubusercontent.com/108955016/218282717-b566d052-d7de-4b5c-bb47-8d69e4be526f.mov

I tried to visualize it.

**Comment by tunntun** [comment]
![image](https://user-images.githubusercontent.com/108955016/218282839-be9b2b00-b5d4-4dfa-807d-35af0f706a09.png)
@hantuzun made this one and I like it so much maybe the button can be blue

**Comment by TeenaBatra** [comment]
@hatunn I liked this idea right above and I also feel adding a blue color to the button would also increase its visibility, making it more likely to be clicked.

**Comment by hantuzun** [comment]
I need opinions on the color of the button. 

I don't think it should be blue. The website uses tones of gray and red. Rarely rose to bring hue difference with red.

I prefer this one, over a red button. The element will be collapsed, so the plus button will have less elements to complete on attention.

OTOH, it's more important to increase the ratio of visitors clearly noticing the button. What do you guys prefer?

**Comment by hantuzun** [comment]
The button in the example above has the following code:

```
<button
  type="button"
  className="relative ml-3 inline-flex items-center rounded-md border border-gray-300 bg-white px-2 py-2 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50"
>
  <PlusIcon className="h-5 w-5" aria-hidden="true" />
</button>
```

It when clicked, the description and the rest of the card should expand with a smooth animation as the button turns to `MinusIcon`. Clicking `MinusIcon` button should collapse the card.

Bonus: The whole title section except the close periphery of Twitter and Website buttons should have the same behavior as the +/- button but with [cursor-default](https://tailwindcss.com/docs/cursor).

**Comment by tunntun** [comment]
https://user-images.githubusercontent.com/108955016/218306479-2429d987-5456-4d07-a262-dce1d73f4baf.mov

how about that? I also add a hover state for the opened one and make everything red. @hantuzun @tervelix @TeenaBatra
