### ISSUE TITLE
Edit text content

### ISSUE THREAD

**Issue by hantuzun** [neu-fi/turkey-relief-dao#28]
The hero section and the rest of the texts should be edited.

**Comment by hantuzun** [comment]
What about this subtitle:

### Donate to one of 14 efforts using credit cards, bank transfers, 16 blockchain networks, and more.

**Comment by TeenaBatra** [comment]
Hi @hantuzun, I really appreciate the great work that you and your team are doing for the people of Turkey during this difficult time. I am a beginner to these tech stacks, but please let me know if I can contribute to any open issues. I'll try my best to help with that.

**Comment by hantuzun** [comment]
Hi Teena. I'd really like to have any kind of help. Please consider contributing to "no code" issues. Or anything else you think that can help. Noticing bugs or writing content better, coming up with ideas are all fair game.

**Comment by haticecs** [comment]
Hi, is the content final for other texts? If you can share it with me, I can update them all.

**Comment by hantuzun** [comment]
Hi @haticecs, no I'm not sure what to write...

The one I propose above is a good option in my opinion and it its numbers could easily be populated from the data.

What do you think?

**Comment by haticecs** [comment]
I think it is clear and good. I actually contacted you through twitter @hantuzun

**Comment by hantuzun** [comment]
Ok, now it's two of us agreeing on the text. Someone can work on it.

@haticecs I'll read my DMs.

**Comment by haticecs** [comment]
Let me work on that, thanks @hantuzun !

**Comment by hantuzun** [comment]
Fixed with #49. I'll close this one. Feel free to open other issues for other texts, or the subtitle.
