### ISSUE TITLE
Update the casuality statistics

### ISSUE THREAD

**Issue by hantuzun** [neu-fi/turkey-relief-dao#29]
<img width="472" alt="Screen Shot 2023-02-10 at 15 29 04" src="https://user-images.githubusercontent.com/2770895/218092728-1d923eb1-1078-4f7e-bd62-674ae873fb87.png">

3 of the 4 stats here (except the magnitude) need to be updated.
Please suggest:
* A statistics
* Its description with bold word(s) in the beginning.
* Trusted resource link in English, strongly prefered without a paywall.

**Comment by tervelix** [comment]
Can we extract the live data directly from AFAD or any other resources?

https://www.afad.gov.tr/kahramanmarasta-meydana-gelen-depremler-hkbasin-bulteni27

**Comment by tervelix** [comment]
We can add more statics imo.

Rescued people: 80.088 (https://www.afad.gov.tr/kahramanmarasta-meydana-gelen-depremler-hkbasin-bulteni27)
number of people evacuated: 102.388
Damaged Buildings: 12,376

11.02.2023 (TR)

Death Toll: 20.937 
Collapsed Buildings: 6.444 (source: https://www.ntv.com.tr/galeri/turkiye/yuzyilin-felaketi-kahramanmaras-merkezli-depremlerde-can-kaybi-ve-yarali-sayisinda-son-durum,PuIEUTHvEEGnugRgTIFyDA)

**Comment by hantuzun** [comment]
I've updated them last night. Could you check out if we can update them further? But the resources should be in English as we target foreigners.

**Comment by tervelix** [comment]
Death Toll:  29.605

**Comment by selmanyalcin** [comment]
![resim_2023-02-13_222613159](https://user-images.githubusercontent.com/102980368/218554621-2ea57ac3-76c0-4053-9998-813a1d935d73.png)

I have updated it also looked for an API for fetching death toll count but ı couldn't find an API

**Comment by tervelix** [comment]
yeha, i couldn't find any API either.
