### ISSUE TITLE
Add Anka's Optimism wallet

### ISSUE THREAD

**Issue by hantuzun** [neu-fi/turkey-relief-dao#31]
Need to add Optimism as a Network, filter, and icon first. Then add their Optimism address: https://ankarelief.org/

**Comment by tervelix** [comment]
`      {
        type: 'cryptocurrency',
        name: 'Optimism',
        address: '0xb88A1deaE6a5dA84B15BBD272E550bd9e87b8a5B',
        sourceUrls: ['https://ankarelief.org/#donation'],
      {`

**Comment by hantuzun** [comment]
Optimism network must be added as well. There's issue requiring that, the Connext issue.

**Comment by hantuzun** [comment]
Closed with #43
