### ISSUE TITLE
Add Aptos wallets

### ISSUE THREAD

**Issue by hantuzun** [neu-fi/turkey-relief-dao#32]
Need to add Aptos as a Network, filter, and icon first. Then add 3+ Aptos addresses: https://www.paribu.com/blog/haberler/afet-destek-planimiz-ve-kripto-para-ile-bagis-organizasyonu-hakkinda/

https://twitter.com/TurkeyReliefDAO/status/1624051944632340486

**Comment by TeenaBatra** [comment]
Hi @hantuzun, I would like to give this issue a try. I have already made changes in the code to accommodate Aptos as a network, filter, and icon, but can you help me understand what is meant by 'adding 3+ Aptos addresses'? Where should aptos be added? Under all organizations or just a specific one? - Thanks in advance!

**Comment by tervelix** [comment]
Hi @TeenaBatra! You can find APTOS wallets on here: https://www.paribu.com/blog/haberler/afet-destek-planimiz-ve-kripto-para-ile-bagis-organizasyonu-hakkinda/

Search for APT.

**Comment by TeenaBatra** [comment]
Hi @tervelix, Thank you for your response. I understood where I can obtain the APT addresses. Can you please clarify whether PARIBU should be added as a separate organization (such as AHBAP or AFAD), or if the APT wallet address should be included under any existing organization?
Thanks!

**Comment by tervelix** [comment]
Hi @TeenaBatra , Paribu is a CEX which holds custody for wallets. You should refer the organization which apt wallet has been listed under, such as Afad or NeedsMap.


![image](https://user-images.githubusercontent.com/88801996/218269128-d3199c22-57af-4275-bbe9-28e0b52c8720.png)

**Comment by TeenaBatra** [comment]
@tervelix Thank you so much for the clarification and all of your help. I truly appreciate it.

**Comment by TeenaBatra** [comment]
Hi @hantuzun, Kindly review the changes and merge it if looks good.
PR: #40 
Please let me know if any other updates is needed. I would definitely work on that.

**Comment by TeenaBatra** [comment]
@hantuzun @tervelix Thank you guys for helping me with this issue....This was technically my first PR...I'm so glad....It couldn't be possible without your assistance.
I would like to pick up some more issues for sure.

**Comment by tervelix** [comment]
WE re glad for any kind of help. This was also my first PR, happy to help you! <3

**Comment by hantuzun** [comment]
Thanks a lot guys!
