### ISSUE TITLE
Add sharable filters functionality

### ISSUE THREAD

**Issue by hantuzun** [neu-fi/turkey-relief-dao#36]
What about a button appears at the bottom of filters when filters are applied? A button that says:
"Copy URL for this filter"

Clicking that could copy a URL like the following:
https://turkiyereliefdao.com?cryptocurrencies=Polkadot

When such a URL is loaded, the query parameters must be deleted and the state better is persisted (#35) on page refreshes.

Another button next to it could say:
"Reset filter"

Advantage: 
 * Relevant subsets of options could be shared with networks, resulting in better targeting and conversion.
 
Disadvantages:
 *Harder to implement than most of the other issues i.e. opportunity cost.
 
 [1] Need to create persistent state management.  Even more work. Could be delegated to another issue. The disadvantage of this

**Comment by oytuncoban** [comment]
Closing the issue since it's resolved in #71.
