### ISSUE TITLE
Add Arbitrum and Optimism to Ahbap

### ISSUE THREAD

**Issue by hantuzun** [neu-fi/turkey-relief-dao#37]
Add the new bridged L2 assets to Ahbap.

### Arbitrum
 * https://twitter.com/ConnextNetwork/status/1624413520258379776
 * https://arbiscan.io/address/0x8888759373137b84e9f0ef13ecb13e321c251ee3#readContract
 
 ### Optimism
 * https://twitter.com/ConnextNetwork/status/1624413520258379776
 * https://optimistic.etherscan.io/address/0x8888759373137b84e9f0ef13ecb13e321c251ee3#readContract
 
 Add info: "Bridged through a trustless and audited contract"

**Comment by tervelix** [comment]
I've done this. How and where can i add the code?

**Comment by hantuzun** [comment]
I commented on the PR @tervelix.

**Comment by hantuzun** [comment]
Read: https://github.com/neu-fi/turkiye-relief-dao/pull/41#issuecomment-1426990115
