### ISSUE TITLE
Add Hold My Hand NFTs

### ISSUE THREAD

**Issue by hantuzun** [neu-fi/turkey-relief-dao#38]
* https://twitter.com/houseofmat_/status/1623837198863720452
* https://forturkey.art

**Comment by hantuzun** [comment]
A young solidity developer I know told me he reviewed the contracts. But someone else needs to audit them!

**Comment by selmanyalcin** [comment]
![Screenshot_2023-02-14-22-01-53-126_com.android.chrome.jpg](https://user-images.githubusercontent.com/102980368/218832407-4c7d6a01-a642-4b69-bd0b-aa43a6d45417.jpg)

I have added collection but someone should upload logo to icons folder and if you want you can check collection informations
