### ISSUE TITLE
Delete old Ahbap Multi-Sig adresses while they have been changed with new BTCTürk NGO adresses

### ISSUE THREAD

**Issue by tervelix** [neu-fi/turkey-relief-dao#39]
source:
1- https://twitter.com/TheBullduck/status/1624389815016751105
2- https://donation.btcturk.com/

**Comment by hantuzun** [comment]
Ahbap has shared a tweet: https://discord.com/channels/1073302047618760765/1073324124509847602/1074029701384913007

The multisig addresses are not deprecated. We've just had a call on this and the consensus was to keep the existing addresses. 

@tervelix you could close this issue for now if you agree.

**Comment by tervelix** [comment]
I agree
