### ISSUE TITLE
Reduce margins for donation cards in the smallest mobile views

### ISSUE THREAD

**Issue by hantuzun** [neu-fi/turkey-relief-dao#53]
This's a donation organization card in the smallest supported view size of 375px (iPhone SE).

<img width="283" alt="Screen Shot 2023-02-12 at 16 01 03" src="https://user-images.githubusercontent.com/2770895/218312603-c35affa0-b390-4c56-820f-683dd7f826d9.png">

It should have a smaller margin in my opinion. I mean the margins around the card to the edges of the screen.

**Comment by selmanyalcin** [comment]
I think it's looking pretty good anyway but we can fix it
