### ISSUE TITLE
Remove focus rings from filter checkboxes

### ISSUE THREAD

**Issue by hantuzun** [neu-fi/turkey-relief-dao#70]
Here's the current look.

<img width="214" alt="Screen Shot 2023-02-13 at 03 32 05" src="https://user-images.githubusercontent.com/2770895/218346816-b6ef0c88-56d6-45fd-a650-f5644d6a046e.png">

There's no use of the focus element, except accessibility. We do not support accessibility at the moment. I suggest we remove focus rings from these checkboxes.

**Comment by yigitfindikli** [comment]
Fixed in https://github.com/neu-fi/turkiye-relief-dao/pull/68
