### ISSUE TITLE
Shorten all non-address texts (linkNames) to fit in mobile views

### ISSUE THREAD

**Issue by hantuzun** [neu-fi/turkey-relief-dao#80]
This is how the website works on mobile screens.

<img width="476" alt="Screen Shot 2023-02-14 at 01 15 52" src="https://user-images.githubusercontent.com/2770895/218586884-81538ecd-d860-4604-9425-6795cfe74057.png">

Reword all the linkNames, so that they all fit in this view (iPhone SE 375px width)

The relevant file: https://github.com/neu-fi/turkiye-relief-dao/blob/main/config/donations.ts

**Comment by oytuncoban** [comment]
@hantuzun How about making the text area grows by height rather than an ellipsis?
I think we should improve the UI design here instead of limiting the words for editors.
