### ISSUE TITLE
Addresses gets duplicated when toogles are interacted with

### ISSUE THREAD

**Issue by hantuzun** [neu-fi/turkey-relief-dao#9]
Some organizations have accounts with the same names such as "Tron" and "Tron" again. They do this for supporting multiple exchanges.

However, the state management mishandles these. It creates duplicates if you toogle cryptocurrencies.

**Comment by MhmtMutlu** [comment]
If you explain bug and desired solution a bit more, I would like to fix it.

**Comment by oytuncoban** [comment]
Maybe we can close this issue since it's resolved with [dd87d12](https://github.com/neu-fi/turkiye-relief-dao/commit/dd87d129382f3c19059ee8acc4ac354418cadda0) @hantuzun?

**Comment by oytuncoban** [comment]
Fixed with [dd87d12](https://github.com/neu-fi/turkiye-relief-dao/commit/dd87d129382f3c19059ee8acc4ac354418cadda0), closing.
