### ISSUE TITLE
Opening in a New Tab

### ISSUE THREAD

**Issue by mrtdlgc** [neu-fi/turkey-relief-dao#91]
When I click on any link on the website, it directly follows the link. Instead, in terms of UX, it would be better to just open them in a new tab. Easy fix, just don't know how to make a PR.

**Comment by hantuzun** [comment]
This behavior is by design. Here're a few reasons for this:
 * https://uxdesign.cc/linking-to-a-new-tab-vs-same-tab-f88b495d2187
 * https://ux.stackexchange.com/questions/104154/should-external-link-open-in-same-tab-or-new-tab
